// ─── APP CONFIG ───────────────────────────────────────────────────────────────
// Keyed by NEXT_PUBLIC_APP_MODE. Add new modes here without touching app code.

const configs = {
  // ── EDUCATOR ─────────────────────────────────────────────────────────────────
  educator: {
    appMode: "educator",
    appTitle: "LogIt",
    appSubtitle: "Teacher Incident Log",
    appDescription:
      "Speak for 30 seconds. LogIt instantly turns your voice note into a professional, FERPA-aware incident report ready for your school portal.",
    tagline: "For K–12 teachers",
    supportEmail: "cierolink@gmail.com",
    company: "CieroLink LLC",
    freeTierLabel: "Free tier: 10 logs/month",
    freeLimit: 10,
    footerNote: "Built for K–12 teachers · Not affiliated with any school district",
    logExportHeader: "LOGIT DOCUMENTATION REPORT",
    logExportFooter: "Generated by LogIt · CieroLink LLC\nAll student names replaced per FERPA guidelines",
    privacyNote: "FERPA-Aware",
    ctaLabel: "🎙️ Start Logging",
    emptyLogText: "No logs yet.\nTap Record to create your first log.",
    copyPortalLabel: "Copy for Portal",
    howItWorksSteps: [
      ["Tap and speak", "Describe the incident in plain language. No scripts, no forms."],
      ["AI writes the report", "Names replaced, professional format, FERPA-aware. In seconds."],
      ["Copy for portal", "Paste into PowerSchool, Infinite Campus, or any school system."],
    ],
    features: [
      { icon: "🎙️", bg: "rgba(230,57,70,0.12)", title: "Voice-to-report in seconds", sub: "No typing. Just speak and let AI handle the rest." },
      { icon: "🔒", bg: "rgba(67,97,238,0.12)", title: "FERPA-aware name scrubbing", sub: "Student names automatically replaced before AI processing." },
      { icon: "📋", bg: "rgba(45,158,117,0.12)", title: "District form generation", sub: "Automatic fill-in for Philly SDP, Delco, PA, and NJ forms." },
    ],

    // ── Colors ──────────────────────────────────────────────────────────────
    colors: {
      primary: "#E63946",
      primaryBg: "rgba(230,57,70,0.12)",
      secondary: "#4361EE",
      secondaryBg: "rgba(67,97,238,0.12)",
      accent: "#C9A84C",
      appBg: "#0A0A0F",
      shellLight: "#F8FAFF",
      shellDark: "#111118",
      borderLight: "#E0E8F5",
      textPrimary: "#0A0F1E",
      textMuted: "#7A8AAA",
    },

    // ── Categories ──────────────────────────────────────────────────────────
    cats: {
      behavioral: {
        label: "Behavioral",
        color: "#E63946",
        bg: "rgba(230,57,70,0.12)",
      },
      academic: {
        label: "Academic",
        color: "#4361EE",
        bg: "rgba(67,97,238,0.12)",
      },
      parent_contact: {
        label: "Parent Contact",
        color: "#2D9E75",
        bg: "rgba(45,158,117,0.12)",
      },
      intervention: {
        label: "Intervention",
        color: "#9D4EDD",
        bg: "rgba(157,78,221,0.12)",
      },
      positive: {
        label: "Positive Note",
        color: "#C9A84C",
        bg: "rgba(201,168,76,0.12)",
      },
    },

    // ── Keywords for auto-categorization ────────────────────────────────────
    keywords: {
      behavioral: [
        "disruptive", "disruption", "disrespectful", "refusal", "refused",
        "yelling", "arguing", "fight", "fighting", "hit", "pushed", "kicked",
        "bullying", "threat", "unsafe", "off task", "out of seat",
        "inappropriate", "profanity", "defiant", "eloped", "left class",
        "skipped", "tardy", "redirection", "consequence",
      ],
      academic: [
        "missing work", "incomplete", "failed", "failing", "quiz", "test",
        "assignment", "homework", "classwork", "participation", "not prepared",
        "did not submit", "late work", "grade", "grades", "progress",
        "intervention", "tutoring", "support", "accommodations", "iep", "504",
        "reading", "math", "writing",
      ],
      parent_contact: [
        "called parent", "emailed parent", "parent conference", "guardian",
        "voicemail", "left message", "spoke with mom", "spoke with dad",
        "contact home", "family notified", "parent pickup", "meeting scheduled",
        "follow up with parent", "texted parent", "parent response",
      ],
    },

    // ── District picker ──────────────────────────────────────────────────────
    districts: [
      { id: "none",       label: "Standard only",     state: "",   icon: "🚫" },
      { id: "philly_sdp", label: "Philadelphia SDP",  state: "PA", icon: "📋" },
      { id: "delco",      label: "Delaware County",   state: "PA", icon: "📋" },
      { id: "pa_generic", label: "Pennsylvania",      state: "PA", icon: "📋" },
      { id: "nj_generic", label: "New Jersey",        state: "NJ", icon: "📋" },
    ],

    // ── District report field definitions ───────────────────────────────────
    districtForms: {
      nj_generic: [
        {
          title: "New Jersey Report",
          source: "nj_report",
          fields: [
            "incident_classification",
            "hib_determination",
            "location",
            "time_of_day",
            "witnesses",
            "parent_guardian_notified",
            "law_enforcement_notified",
            "details",
            "interventions_used",
          ],
        },
      ],
      philly_sdp: [
        {
          title: "Behavior Referral",
          source: "behavior_referral",
          fields: [
            "alignment",
            "title",
            "incident_time_frame_code",
            "context_description",
            "location_description",
            "details",
            "damages",
          ],
        },
        {
          title: "OSR-5 Statement",
          source: "osr5_statement",
          fields: ["date", "location", "narrative", "persons_involved"],
        },
      ],
      delco: [
        {
          title: "District Report",
          source: "district_report",
          fields: [
            "incident_type",
            "location",
            "witnesses",
            "parent_notified",
            "administrator_notified",
            "details",
            "recommended_consequence",
          ],
        },
      ],
      pa_generic: [
        {
          title: "Pennsylvania Report",
          source: "pa_report",
          fields: [
            "incident_type",
            "location",
            "time_frame",
            "witnesses",
            "parent_notified",
            "administrator_notified",
            "police_notified",
            "details",
            "action_taken",
          ],
        },
      ],
    },

    // ── AI prompt extras per district ────────────────────────────────────────
    districtPrompts: {
      philly_sdp:
        "generate behavior_referral with fields: alignment, title, incident_time_frame_code, context_description, location_description, details, damages. Also generate osr5_statement with fields: date, location, narrative (first person), persons_involved",
      delco:
        "generate district_report with fields: incident_type (Physical Altercation|Verbal Altercation|Insubordination|Property Damage|Bullying|Other), location, witnesses, parent_notified, administrator_notified, details, recommended_consequence",
      pa_generic:
        "generate pa_report with fields: incident_type (Physical Altercation|Verbal Altercation|Insubordination|Property Damage|Bullying|Weapons|Substance|Other), location, time_frame, witnesses, parent_notified, administrator_notified, police_notified, details, action_taken",
      nj_generic:
        "generate nj_report with fields: incident_classification (HIB - Harassment Intimidation Bullying|Physical Altercation|Insubordination|Vandalism|Substance|Other), location, time_of_day, witnesses, hib_determination (Yes|No|Under Investigation), parent_guardian_notified, law_enforcement_notified, details, interventions_used",
    },

    // ── Filters shown on the logs screen ────────────────────────────────────
    logFilters: [
      { id: "all",            label: "All" },
      { id: "behavioral",     label: "Behavioral" },
      { id: "academic",       label: "Academic" },
      { id: "parent_contact", label: "Parent Contact" },
      { id: "intervention",   label: "Intervention" },
      { id: "positive",       label: "Positive" },
    ],

    // ── Result screen field definitions ─────────────────────────────────────
    resultFields: [
      { label: "Description",  key: "description",  rows: 3 },
      { label: "Action Taken", key: "action_taken", rows: 2 },
      { label: "Follow-Up",    key: "follow_up",    rows: 2 },
    ],

    // ── Default category when keyword match fails ────────────────────────────
    defaultCategory: "behavioral",

    // ── Privacy footer note shown on result screen ───────────────────────────
    privacyFooter: "🔒 Student names replaced · Stored locally only",

    // ── Upgrade sheet (shown at free limit) ──────────────────────────────────
    upgrade: {
      headline: "Unlimited logs, every month",
      sub: "Keep documenting after your 10 free logs — no more end-of-month rationing.",
      price: "$7/mo",
      priceNote: "planned launch price",
      bullets: [
        "Unlimited voice logs every month",
        "All district form templates included",
        "Priority support from a fellow educator-builder",
      ],
      cta: "Join the waitlist",
      note: "No charge today — we'll email you when unlimited launches.",
    },
  },

  // ── TRADE (Field Service / Plumbing) ─────────────────────────────────────────
  trade: {
    appMode: "trade",
    appTitle: "ServiceLog",
    appSubtitle: "Field Service Job Log",
    appDescription:
      "Speak for 30 seconds. ServiceLog turns your voice note into a professional job record — repairs, estimates, PM visits, and parts orders — ready for your CRM or work order system.",
    tagline: "FOR FIELD SERVICE PROS",
    supportEmail: "cierolink@gmail.com",
    company: "CieroLink LLC",
    freeTierLabel: "Free tier: 10 logs/month",
    freeLimit: 10,
    footerNote: "Built for field service professionals",
    logExportHeader: "SERVICELOG JOB REPORT",
    logExportFooter: "Generated by ServiceLog · CieroLink LLC",
    privacyNote: "Client Data Protected",
    ctaLabel: "🎙️ Start Logging",
    emptyLogText: "No jobs logged yet.\nTap Record to log your first job.",
    copyPortalLabel: "Copy for Work Order",
    howItWorksSteps: [
      ["Tap and speak", "Describe the job in plain language. No paperwork, no typing on-site."],
      ["AI writes the report", "Job type auto-detected, professional format, ready in seconds."],
      ["Copy for your system", "Paste into your CRM, ServiceTitan, Jobber, or email."],
    ],
    features: [
      { icon: "🎙️", bg: "rgba(244,129,31,0.12)", title: "Voice-to-report on the job", sub: "Log repairs, estimates, and PM notes hands-free." },
      { icon: "🔧", bg: "rgba(26,109,181,0.12)",  title: "Auto-categorized job type", sub: "Repair, estimate, maintenance, or parts order — detected from your words." },
      { icon: "📋", bg: "rgba(45,158,117,0.12)", title: "Work order ready", sub: "Structured output ready to paste into ServiceTitan, Jobber, or email." },
    ],

    // ── Colors ──────────────────────────────────────────────────────────────
    colors: {
      primary: "#F4811F",
      primaryBg: "rgba(244,129,31,0.12)",
      secondary: "#1A6DB5",
      secondaryBg: "rgba(26,109,181,0.12)",
      accent: "#C9A84C",
      appBg: "#0A0A0F",
      shellLight: "#F7F9FC",
      shellDark: "#111118",
      borderLight: "#DDE6F0",
      textPrimary: "#0C1220",
      textMuted: "#6A7A96",
    },

    // ── Categories ──────────────────────────────────────────────────────────
    cats: {
      repair_job: {
        label: "Repair",
        color: "#E63946",
        bg: "rgba(230,57,70,0.12)",
      },
      estimate: {
        label: "Estimate",
        color: "#1A6DB5",
        bg: "rgba(26,109,181,0.12)",
      },
      maintenance: {
        label: "Preventative Maintenance",
        color: "#2D9E75",
        bg: "rgba(45,158,117,0.12)",
      },
      parts_order: {
        label: "Parts Required",
        color: "#F4811F",
        bg: "rgba(244,129,31,0.12)",
      },
    },

    // ── Keywords for auto-categorization ────────────────────────────────────
    keywords: {
      repair_job: [
        "leaking", "leak", "dripping", "drip", "burst", "broke", "broken",
        "clogged", "blockage", "backed up", "overflow", "flooding", "flood",
        "no hot water", "no water", "low pressure", "pressure drop",
        "running toilet", "toilet won't flush", "garbage disposal",
        "water heater", "pipe burst", "sewer backup", "drain slow",
        "faucet dripping", "shut off valve", "emergency", "repair",
        "fixed", "replaced", "installed", "snake", "augered", "rodded",
      ],
      estimate: [
        "quote", "estimate", "pricing", "cost", "how much", "proposal",
        "bid", "gave price", "customer approved", "customer declined",
        "scope of work", "invoice", "labor hours", "materials cost",
        "line item", "total", "approval needed", "pending approval",
      ],
      maintenance: [
        "pm", "preventative", "preventive", "maintenance visit", "annual",
        "inspection", "tune-up", "flush", "flushing", "descale", "descaling",
        "anode rod", "filter change", "filter replacement", "clean out",
        "backflow test", "pressure test", "water test", "checked",
        "routine", "scheduled", "service agreement", "service contract",
      ],
      parts_order: [
        "ordered", "order", "parts", "part number", "need part",
        "backordered", "in stock", "out of stock", "supply house",
        "waiting on part", "part arriving", "will call",
        "valve", "cartridge", "flapper", "wax ring", "p-trap",
        "supply line", "shut-off", "coupling", "fitting", "gasket",
        "expansion tank", "pressure relief valve", "thermocouple",
      ],
    },

    // ── Districts equivalent: service regions / territory ────────────────────
    // Repurposed as "service region" picker for field workers
    districts: [
      { id: "none",      label: "No region",         state: "",   icon: "🚫" },
      { id: "residential", label: "Residential",     state: "",   icon: "🏠" },
      { id: "commercial",  label: "Commercial",      state: "",   icon: "🏢" },
      { id: "industrial",  label: "Industrial",      state: "",   icon: "🏭" },
      { id: "emergency",   label: "Emergency Call",  state: "",   icon: "🚨" },
    ],

    // ── No district-specific form templates for trade mode ───────────────────
    districtForms: {},
    districtPrompts: {},

    // ── Filters shown on the logs screen ────────────────────────────────────
    logFilters: [
      { id: "all",         label: "All" },
      { id: "repair_job",  label: "Repair" },
      { id: "estimate",    label: "Estimate" },
      { id: "maintenance", label: "PM" },
      { id: "parts_order", label: "Parts" },
    ],

    // ── Result screen field definitions ─────────────────────────────────────
    resultFields: [
      { label: "Job Description", key: "description",  rows: 3 },
      { label: "Work Performed",  key: "action_taken", rows: 2 },
      { label: "Next Steps",      key: "follow_up",    rows: 2 },
    ],

    // ── Default category when keyword match fails ────────────────────────────
    defaultCategory: "repair_job",

    // ── Privacy footer note shown on result screen ───────────────────────────
    privacyFooter: "🔒 Client info protected · Stored locally only",

    // ── Typed job metadata field (not spoken — keeps PII out of audio) ───────
    metadataField: {
      key: "job_ref",
      label: "Job Reference",
      placeholder: "Job # or street name — typed, never spoken",
    },

    // ── Field Service Summary panels on the result screen ────────────────────
    // accent: "primary"/"secondary" resolve to mode colors; otherwise literal hex.
    tradeSummaryFields: [
      { label: "Client Issue",           key: "client_issue",           accent: "primary"   },
      { label: "Diagnostic Findings",    key: "diagnostic_findings",    accent: "secondary" },
      { label: "Materials Used",         key: "materials_used",         accent: "#2D9E75"   },
      { label: "Recommended Next Steps", key: "recommended_next_steps", accent: "#C9A84C"   },
    ],

    // ── Customer-facing share message ─────────────────────────────────────────
    customerShare: {
      buttonLabel: "Send to Customer",
      intro: "Here's a summary of today's service visit:",
      foundLabel: "WHAT WE FOUND",
      didLabel: "WHAT WE DID",
      nextLabel: "WHAT'S NEXT",
      signoff: "Questions? Just reply to this message.",
    },

    // ── Upgrade sheet (shown at free limit) ──────────────────────────────────
    upgrade: {
      headline: "Unlimited job logs",
      sub: "Don't stop logging mid-month. Unlimited jobs, photos, and customer summaries.",
      price: "$12/mo",
      priceNote: "planned launch price",
      bullets: [
        "Unlimited voice job logs every month",
        "Photo documentation on every job",
        "Customer-ready summaries by text or email",
      ],
      cta: "Join the waitlist",
      note: "No charge today — we'll email you when unlimited launches.",
    },
  },
};

// ─── EXPORTS ──────────────────────────────────────────────────────────────────

const mode = process.env.NEXT_PUBLIC_APP_MODE || "educator";
const appConfig = configs[mode] || configs.educator;

export default appConfig;
export { configs };
